name: Docker

on:
  push:
    paths:
    - .github/workflows/docker.yaml
    - '**/Dockerfile'
    - '**/docker-entrypoint.sh'

jobs:

  build-1_10:

    name: Build 1.10
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build .
      working-directory: '1.10'

  build-2_0:

    name: Build 2.0
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build .
      working-directory: '2.0'
