name: Docker - v2 LTS

on:
  pull_request: null
  push:
    paths:
      - .github/workflows/v2-lts.yaml
      - '2.2/**'

env:
  AWS_REGION: us-east-1
  ECR_REPO: public.ecr.aws/u0u1j5s3/composer

jobs:
  build-lts:
    name: Build LTS version
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        version:
          - "2.2"
    steps:
      - uses: actions/checkout@v4
      - name: "Determine composer version from Dockerfile"
        uses: "./.github/actions/determine-composer-version"
        with:
          working-directory: "${{ matrix.version }}"
      # Build full image: binary with runtime
      - name: Build full image
        working-directory: ${{ matrix.version }}
        run: |
          docker build \
          --pull \
          --no-cache \
          --target binary-with-runtime \
          --tag composer/composer:lts \
          --tag composer/composer:${{ env.COMPOSER_VERSION_MAJOR_MINOR }} \
          --tag composer/composer:${{ env.COMPOSER_VERSION_MAJOR_MINOR_PATCH }} \
          .
      # Build low-size image with binary only
      - name: Build binary-only image
        working-directory: ${{ matrix.version }}
        run: |
          docker build \
          --pull \
          --no-cache \
          --target standalone-binary \
          --tag composer/composer:lts-bin \
          --tag composer/composer:${{ env.COMPOSER_VERSION_MAJOR_MINOR }}-bin \
          --tag composer/composer:${{ env.COMPOSER_VERSION_MAJOR_MINOR_PATCH }}-bin \
          .
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push tag(s) to Docker Hub
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ matrix.version }}
        run: |
          docker push composer/composer:lts
          docker push composer/composer:lts-bin
          docker push composer/composer:${{ env.COMPOSER_VERSION_MAJOR_MINOR }}
          docker push composer/composer:${{ env.COMPOSER_VERSION_MAJOR_MINOR }}-bin
          docker push composer/composer:${{ env.COMPOSER_VERSION_MAJOR_MINOR_PATCH }}
          docker push composer/composer:${{ env.COMPOSER_VERSION_MAJOR_MINOR_PATCH }}-bin
      - name: Login to Amazon Public ECR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ECR_ACCESS_KEY }}
          password: ${{ secrets.AWS_ECR_SECRET_KEY }}
      - name: Push tag(s) to Amazon Public ECR
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ matrix.version }}
        run: |
          docker tag composer/composer:lts ${{ env.ECR_REPO }}:lts
          docker tag composer/composer:lts-bin ${{ env.ECR_REPO }}:lts-bin
          docker tag composer/composer:${{ env.COMPOSER_VERSION_MAJOR_MINOR }} ${{ env.ECR_REPO }}:${{ env.COMPOSER_VERSION_MAJOR_MINOR }}
          docker tag composer/composer:${{ env.COMPOSER_VERSION_MAJOR_MINOR }}-bin ${{ env.ECR_REPO }}:${{ env.COMPOSER_VERSION_MAJOR_MINOR }}-bin
          docker tag composer/composer:${{ env.COMPOSER_VERSION_MAJOR_MINOR_PATCH }} ${{ env.ECR_REPO }}:${{ env.COMPOSER_VERSION_MAJOR_MINOR_PATCH }}
          docker tag composer/composer:${{ env.COMPOSER_VERSION_MAJOR_MINOR_PATCH }}-bin ${{ env.ECR_REPO }}:${{ env.COMPOSER_VERSION_MAJOR_MINOR_PATCH }}-bin
          docker push ${{ env.ECR_REPO }}:lts
          docker push ${{ env.ECR_REPO }}:lts-bin
          docker push ${{ env.ECR_REPO }}:${{ env.COMPOSER_VERSION_MAJOR_MINOR }}
          docker push ${{ env.ECR_REPO }}:${{ env.COMPOSER_VERSION_MAJOR_MINOR }}-bin
          docker push ${{ env.ECR_REPO }}:${{ env.COMPOSER_VERSION_MAJOR_MINOR_PATCH }}
          docker push ${{ env.ECR_REPO }}:${{ env.COMPOSER_VERSION_MAJOR_MINOR_PATCH }}-bin
